(define (problem gripper-problem)
    (:domain gripper-continuous)

    (:objects
        mover1 mover2 - mover
        crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - crate
        loader1 loader2 - loader
        A B C - group
    )

    (:init
        (mover mover1)
        (mover mover2)
        (free mover1)
        (free mover2)
        (equal mover1 mover1)
        (equal mover2 mover2)
        (= (rob_position mover1) 0)  
        (= (rob_position mover2) 0)  
        (not (moving mover1))
        (not (moving mover2))
        (= (battery mover1) 20)
        (= (battery mover2) 20)
        (= (maxBattery) 200)
        
        (= (max_vel mover1) 10)
        (= (max_vel mover2) 10)
        
        (= (velocity mover1) 10)
        (= (velocity mover2) 10)
        
        ; (= (batterytimer) 0)
        
        (crate crate1)
        (crate crate2)
        (crate crate3)
        (crate crate4)
        (crate crate5)
        (crate crate6)
        (crate crate7)
        (crate crate8)
        (crate crate9)
        (not (isLoaded crate1))
        (not (isLoaded crate2))
        (not (isLoaded crate3))
        (not (isLoaded crate4))
        (not (isLoaded crate5))
        (not (isLoaded crate6))
        (not (isLoaded crate7))
        (not (isLoaded crate8))
        (not (isLoaded crate9))
        (= (position crate1) 10)
        (= (position crate2) 20)
        (= (position crate3) 30)
        (= (position crate4) 50)
        (= (position crate5) 60)
        (= (position crate6) 70)
        (= (position crate7) 80)
        (= (position crate8) 90)
        (= (position crate9) 100)
        (= (weight crate1) 7)
        (= (weight crate2) 3)
        (= (weight crate3) 2)
        (= (weight crate4) 6)
        (= (weight crate5) 70)
        (= (weight crate6) 2)
        (= (weight crate7) 60)
        (= (weight crate8) 7)
        (= (weight crate9) 70)
        (not (isFragile crate1))
        (not (isFragile crate2))
        (not (isFragile crate3))
        (not (isFragile crate4))
        (not (isFragile crate5))
        (not (isFragile crate6))
        (not (isFragile crate7))
        (not (isFragile crate8))
        (not (isFragile crate9))
        (= (belong crate1) 3)
        (= (belong crate2) 3)
        (= (belong crate3) 2)
        (= (belong crate4) 2)
        (= (belong crate5) 2)
        (= (belong crate6) 0)
        (= (belong crate7) 1)
        (= (belong crate8) 0)
        (= (belong crate9) 1)
        (= (x) 100)
        (group A)
        (group B)
        (group C)
        (= (numOfGroup A) 1)
        (= (numOfGroup B) 2)
        (= (numOfGroup C) 3)
        (= (elementsPerGroup A) 2)
        (= (elementsPerGroup B) 3)
        (= (elementsPerGroup C) 2)

        (= (currentGroup) 0)

        (loader loader1)
        (= (loaderTimer loader1) 0)
        (not (busyLoading loader1)) 
        (loader loader2)
        (= (loaderTimer loader2) 0)
        (not (busyLoading loader2)) 
        (not (isCheap loader2))
        (not (isCheap loader1))

        (not (currentGroupSet))
    )

    (:goal
        (and 
            (isLoaded crate1)
            (isLoaded crate2)
            (isLoaded crate3)
            (isLoaded crate4)
            (isLoaded crate5)
            (isLoaded crate6)
            (isLoaded crate7)
            (isLoaded crate8)
            (isLoaded crate9)
        )
    )

)
